 
-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.account_id_seq;

CREATE SEQUENCE public.account_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.movement_id_seq;

CREATE SEQUENCE public.movement_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
	opening_balance numeric(38, 2) NOT NULL,
	status bool NOT NULL,
	client_id int8 NOT NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"number" varchar(10) NOT NULL,
	"type" varchar(10) NOT NULL,
	client_name varchar(255) NOT NULL,
	CONSTRAINT account_number_key null,
	CONSTRAINT account_pkey null,
	CONSTRAINT account_type_check null
);


-- public.movement definition

-- Drop table

-- DROP TABLE public.movement;

CREATE TABLE public.movement (
	balance numeric(38, 2) NOT NULL,
	status bool NOT NULL,
	value numeric(38, 2) NOT NULL,
	account int8 NOT NULL,
	date_time timestamp(6) NOT NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"type" varchar(15) NOT NULL,
	CONSTRAINT movement_pkey PRIMARY KEY (id),
	CONSTRAINT movement_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSITO'::character varying, 'RETIRO'::character varying])::text[])))
);
